# Generated by Django 4.2 on 2023-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='timestamp',
            new_name='timeStamp',
        ),
        migrations.AlterField(
            model_name='blog',
            name='authorName',
            field=models.CharField(max_length=200),
        ),
    ]
